cluster-config: "config/slurm/cluster.yaml"
cluster: "sbatch --job-name={cluster.jobname} --nodes={cluster.nodes} --ntasks-per-node={cluster.ntaskspernode} --cpus-per-task={cluster.cpuspertask} --mem-per-cpu={cluster.mempercpu} --time={cluster.time} --account={cluster.account} --partition={cluster.partition} --mail-user={cluster.mailuser} --mail-type={cluster.mailtype} --output={cluster.output} --export=ALL "
jobs: 4998
verbose: true
notemp: true